version: '2'

services:
  fuavserver:
    image: 'fuavserver:latest'
    environment:
      TZ: "Europe/Istanbul"
    build:
      context: .
    container_name: fuavserver
    depends_on:
      - h2db-fuav
    env_file:
      - core.env
    ports:
      - "8080:8080"


  h2db-fuav:
    image: 'oscarfonts/h2'
    container_name: h2db-fuav
    ports:
      - "8082:8081"
    env_file:
      - core.env